openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /v1/transactions:
        servers:
            -
                url: 'https://api.whale-alert.io'
                description: ''
        get:
            parameters:
                -
                    name: X-WA-API-KEY
                    description: API key for whalealert.io
                    schema:
                        type: string
                    in: header
                    required: true
                -
                    name: start
                    description: Starting unix time
                    schema:
                        format: int32
                        type: integer
                    in: query
                    required: true
                -
                    name: cursor
                    description: 'Checkpoint cursor to be given to next transaction request '
                    schema:
                        type: string
                    in: query
                    required: false
                -
                    name: end
                    description: End unix time
                    schema:
                        format: int32
                        type: integer
                    in: query
                    required: false
                -
                    name: min_value
                    description: 'Minimum value of transaction, greater than 500000 requests are free'
                    schema:
                        type: integer
                    in: query
                -
                    name: limit
                    description: 'Maximum transaction count to get back, defaults to 100'
                    schema:
                        type: integer
                    in: query
                    required: false
                -
                    name: currency
                    description: 'Returns transactions for a specific currency code, returns all by default'
                    schema:
                        type: string
                    in: query
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transactions'
                    description: Got transactions
components:
    schemas:
        Transactions:
            title: Root Type for Transactions
            description: ''
            type: object
            properties:
                result:
                    type: string
                cursor:
                    type: string
                count:
                    format: int32
                    type: integer
                transactions:
                    type: array
                    items:
                        type: object
                        properties:
                            blockchain:
                                type: string
                            symbol:
                                type: string
                            id:
                                type: string
                            transaction_type:
                                type: string
                            hash:
                                type: string
                            from:
                                type: object
                                properties:
                                    address:
                                        type: string
                                    owner:
                                        type: string
                                    owner_type:
                                        type: string
                            to:
                                type: object
                                properties:
                                    address:
                                        type: string
                                    owner:
                                        type: string
                                    owner_type:
                                        type: string
                            timestamp:
                                format: int32
                                type: integer
                            amount:
                                format: double
                                type: number
                            amount_usd:
                                format: double
                                type: number
                            transaction_count:
                                format: int32
                                type: integer
            example:
                result: success
                cursor: 757f3137-757f30f5-63f235ec
                count: 3
                transactions:
                    -
                        blockchain: tron
                        symbol: usdt
                        id: '1971269809'
                        transaction_type: transfer
                        hash: edc0b0ee834d821ae2dd507767886171d8b215d520558bf70c86f8e70ba6ea8c
                        from:
                            address: TTKF3mNtSvVDgYkN3iuUoHSRmYjhZS28Q4
                            owner: unknown
                            owner_type: unknown
                        to:
                            address: TSaa7LtRXTBLLFs5eEX1eFrMtnS1YWCLPQ
                            owner: unknown
                            owner_type: unknown
                        timestamp: 1676817873
                        amount: 497888.03
                        amount_usd: 500585.72
                        transaction_count: 1
                    -
                        blockchain: ethereum
                        symbol: usdc
                        id: '1971269943'
                        transaction_type: transfer
                        hash: f01f417a97bea9c3daf1e7fc1740b3779e60f565a784975c76aa6f5d6617f802
                        from:
                            address: 0a4f6ecb214dc1d9acdd99743b4dcc58ccc088b9
                            owner: unknown
                            owner_type: unknown
                        to:
                            address: 1b0e489ea1877962b4661d2a5459868ab2e1f665
                            owner: unknown
                            owner_type: unknown
                        timestamp: 1676817899
                        amount: 2010000
                        amount_usd: 2007304.5
                        transaction_count: 1
                    -
                        blockchain: tron
                        symbol: usdt
                        id: '1971269877'
                        transaction_type: transfer
                        hash: fc886d611c534d0cea827cb03cd5c294a413a6207ff11de92119b83a5609005c
                        from:
                            address: TVVZf1PoyvcSrWSwG8wwbaDYn44oxbYx5J
                            owner: unknown
                            owner_type: unknown
                        to:
                            address: TE55VW7m7aoLQZrK1uu8VJbWvRSrtNjuHH
                            owner: unknown
                            owner_type: unknown
                        timestamp: 1676817900
                        amount: 583936.6
                        amount_usd: 587100.56
                        transaction_count: 1
